# Generated by Django 4.2.26 on 2025-11-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorii',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Opisanie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='kartinka')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Stoimost')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Ckidka')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Kolichesto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Producti',
                'db_table': 'product',
            },
        ),
    ]
