# Generated by Django 4.2.26 on 2025-11-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descriptions',
            new_name='description',
        ),
    ]
